In [ ]:
import shutil
import os
import json
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Automatic acess and organize Any image downloaded that have some csv with the label

## BRACOL example

In [ ]:
#counting files to check, the process can be slow
file_count = sum([len(files) for _, _, files in os.walk('/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/01_original/leaf/images')])
print(f"Total images in path Leaf > images: {file_count}")

Total images in path Leaf > images: 1747

In [ ]:
#strategy_path_name = '01_strategy_full_single_and_cropped_leaves'
destination_strategy_path = '/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/01_original/symptom'

In [ ]:
path = destination_strategy_path #+ '/'+strategy_path_name + '/' + 'train'
folders = [f for f in os.listdir(path) if os.path.isdir(os.path.join(path, f))]
folders

['train', 'val', 'test']

In [ ]:
print('Total files in path symptom')
for folder in folders:
  #counting files to check, the process can be slow
  file_count = sum([len(files) for _, _, files in os.walk(path + "/" +folder)])
  print(f"{folder}: {file_count}")

Total files in path symptom
train: 1539
val: 335
test: 335

Acess and organize files in Leaf path

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/01_original/leaf/dataset.csv')

In [ ]:
df

        id  predominant_stress  miner  rust  phoma  cercospora  severity
0        1                   0      0     0      0           0         0
1        2                   0      0     0      0           0         0
2        3                   0      0     0      0           0         0
3        4                   0      0     0      0           0         0
4        5                   0      0     0      0           0         0
...    ...                 ...    ...   ...    ...         ...       ...
1742  1743                   2      0     1      0           0         2
1743  1744                   2      0     1      0           1         2
1744  1745                   4      0     1      0           1         1
1745  1746                   4      0     0      0           1         1
1746  1747                   2      0     1      0           1         1

[1747 rows x 7 columns]

### select all Ids per disease and copy them to a specific folder

In [ ]:
df.columns.values

array(['id', 'predominant_stress', 'miner', 'rust', 'phoma', 'cercospora',
       'severity'], dtype=object)

#### miner (This example was already runned, just check)

In [ ]:
df.query('miner == 1 and rust == 0 and phoma == 0 and cercospora == 0')

        id  predominant_stress  miner  rust  phoma  cercospora  severity
20      21                   1      1     0      0           0         3
21      22                   1      1     0      0           0         1
22      23                   1      1     0      0           0         1
23      24                   1      1     0      0           0         1
24      25                   1      1     0      0           0         1
...    ...                 ...    ...   ...    ...         ...       ...
1508  1509                   1      1     0      0           0         1
1541  1542                   1      1     0      0           0         1
1561  1562                   1      1     0      0           0         1
1584  1585                   1      1     0      0           0         1
1713  1714                   1      1     0      0           0         1

[322 rows x 7 columns]

In [ ]:
df.query('miner == 1 and rust == 0 and phoma == 0 and cercospora == 0')['id'].values

array([  21,   22,   23,   24,   25,   26,   27,   28,   30,   31,   32,
         33,   34,   36,   38,   39,   41,   42,   43,   44,   46,   47,
         48,   49,   50,   51,   52,   53,   56,   57,   59,   60,   63,
         64,   65,   66,   67,   68,   69,   70,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   85,   86,   87,
         88,   89,  137,  212,  213,  214,  215,  216,  217,  218,  219,
        220,  221,  222,  223,  224,  225,  226,  227,  228,  229,  447,
        575,  576,  580,  584,  585,  588,  607,  620,  622,  662,  678,
        680,  686,  688,  689,  690,  695,  697,  698,  699,  700,  704,
        705,  709,  714,  717,  718,  719,  721,  724,  728,  729,  730,
        731,  732,  737,  744,  748,  754,  755,  757,  761,  762,  765,
        767,  768,  770,  771,  774,  779,  782,  784,  786,  790,  791,
        795,  797,  800,  802,  807,  808,  819,  821,  822,  828,  834,
        835,  836,  838,  839,  840,  844,  850,  851,  855,  856,  857,
        860,  861,  864,  867,  868,  871,  872,  873,  874,  875,  876,
        887,  888,  892,  893,  894,  895,  896,  898,  900,  903,  905,
        906,  907,  908,  914,  916,  920,  922,  923,  926,  929,  931,
        932,  997, 1000, 1002, 1003, 1004, 1005, 1010, 1012, 1014, 1015,
       1017, 1019, 1020, 1021, 1023, 1024, 1025, 1026, 1028, 1029, 1030,
       1032, 1035, 1038, 1040, 1042, 1043, 1044, 1050, 1051, 1053, 1055,
       1056, 1057, 1058, 1059, 1062, 1063, 1064, 1068, 1070, 1072, 1073,
       1074, 1075, 1077, 1078, 1082, 1086, 1088, 1092, 1096, 1097, 1098,
       1102, 1106, 1107, 1108, 1109, 1113, 1114, 1117, 1119, 1120, 1121,
       1123, 1126, 1129, 1130, 1131, 1132, 1133, 1135, 1136, 1137, 1138,
       1139, 1141, 1142, 1144, 1145, 1146, 1147, 1153, 1155, 1157, 1160,
       1161, 1162, 1163, 1165, 1166, 1170, 1171, 1172, 1173, 1176, 1177,
       1182, 1189, 1190, 1192, 1197, 1199, 1203, 1204, 1207, 1208, 1210,
       1211, 1212, 1213, 1216, 1217, 1219, 1222, 1224, 1227, 1305, 1316,
       1322, 1351, 1362, 1451, 1459, 1477, 1482, 1487, 1504, 1509, 1542,
       1562, 1585, 1714])

In [ ]:
#write the name of the class in disease_name_class, this is the only thing that you need to change for each disease and run the rest of the code
disease_name_class = 'Miner'
#here you write exaclty are in the csv 'miner', 'rust', 'phoma', 'cercospora', change for each disease, this code will select a list of ids by disease selected in this example is Miner
list_files = df.query('miner == 1 and rust == 0 and phoma == 0 and cercospora == 0')['id'].values

In [ ]:
list_files

array([  21,   22,   23,   24,   25,   26,   27,   28,   30,   31,   32,
         33,   34,   36,   38,   39,   41,   42,   43,   44,   46,   47,
         48,   49,   50,   51,   52,   53,   56,   57,   59,   60,   63,
         64,   65,   66,   67,   68,   69,   70,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   85,   86,   87,
         88,   89,  137,  212,  213,  214,  215,  216,  217,  218,  219,
        220,  221,  222,  223,  224,  225,  226,  227,  228,  229,  447,
        575,  576,  580,  584,  585,  588,  607,  620,  622,  662,  678,
        680,  686,  688,  689,  690,  695,  697,  698,  699,  700,  704,
        705,  709,  714,  717,  718,  719,  721,  724,  728,  729,  730,
        731,  732,  737,  744,  748,  754,  755,  757,  761,  762,  765,
        767,  768,  770,  771,  774,  779,  782,  784,  786,  790,  791,
        795,  797,  800,  802,  807,  808,  819,  821,  822,  828,  834,
        835,  836,  838,  839,  840,  844,  850,  851,  855,  856,  857,
        860,  861,  864,  867,  868,  871,  872,  873,  874,  875,  876,
        887,  888,  892,  893,  894,  895,  896,  898,  900,  903,  905,
        906,  907,  908,  914,  916,  920,  922,  923,  926,  929,  931,
        932,  997, 1000, 1002, 1003, 1004, 1005, 1010, 1012, 1014, 1015,
       1017, 1019, 1020, 1021, 1023, 1024, 1025, 1026, 1028, 1029, 1030,
       1032, 1035, 1038, 1040, 1042, 1043, 1044, 1050, 1051, 1053, 1055,
       1056, 1057, 1058, 1059, 1062, 1063, 1064, 1068, 1070, 1072, 1073,
       1074, 1075, 1077, 1078, 1082, 1086, 1088, 1092, 1096, 1097, 1098,
       1102, 1106, 1107, 1108, 1109, 1113, 1114, 1117, 1119, 1120, 1121,
       1123, 1126, 1129, 1130, 1131, 1132, 1133, 1135, 1136, 1137, 1138,
       1139, 1141, 1142, 1144, 1145, 1146, 1147, 1153, 1155, 1157, 1160,
       1161, 1162, 1163, 1165, 1166, 1170, 1171, 1172, 1173, 1176, 1177,
       1182, 1189, 1190, 1192, 1197, 1199, 1203, 1204, 1207, 1208, 1210,
       1211, 1212, 1213, 1216, 1217, 1219, 1222, 1224, 1227, 1305, 1316,
       1322, 1351, 1362, 1451, 1459, 1477, 1482, 1487, 1504, 1509, 1542,
       1562, 1585, 1714])

In [ ]:
#create a new folder with the disease_name_class writed
destination_path = f'/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/02_original_organized_by_disease_name/automatic/{disease_name_class}'
os.makedirs(destination_path, exist_ok=False)

In [ ]:
#copy all ids in the list to this destination path created
for i in range(len(list_files)):
  file_path = "/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/01_original/leaf/images/" + str(list_files[i]) + '.jpg'
  shutil.copy(file_path, destination_path)

#counting files to check how many images are copied

file_count = sum([len(files) for _, _, files in os.walk(destination_path)])

print(f"Number of files in {destination_path}: {file_count}")

Number of files in /content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/02_original_organized_by_disease_name/automatic/Miner: 322

#### rust (This example was already runned, just check)

In [ ]:
df.query('rust == 1 and miner == 0 and phoma == 0 and cercospora == 0')

        id  predominant_stress  miner  rust  phoma  cercospora  severity
90      91                   2      0     1      0           0         2
91      92                   2      0     1      0           0         1
92      93                   2      0     1      0           0         1
94      95                   2      0     1      0           0         1
95      96                   2      0     1      0           0         3
...    ...                 ...    ...   ...    ...         ...       ...
1720  1721                   2      0     1      0           0         1
1728  1729                   2      0     1      0           0         1
1733  1734                   2      0     1      0           0         1
1739  1740                   2      0     1      0           0         1
1742  1743                   2      0     1      0           0         2

[349 rows x 7 columns]

In [ ]:
#write the name of the class in disease_name_class, this is the only thing that you need to change for each disease and run the rest of the code
disease_name_class = 'Rust'
#here you write exaclty are in the csv 'miner', 'rust', 'phoma', 'cercospora', change for each disease, this code will select a list of ids by disease selected in this example is Miner
list_files = df.query('rust == 1 and miner == 0 and phoma == 0 and cercospora == 0')['id'].values

In [ ]:
list_files

array([  91,   92,   93,   95,   96,   97,   98,   99,  101,  102,  103,
        104,  105,  106,  107,  108,  109,  110,  111,  112,  113,  114,
        115,  116,  118,  119,  120,  122,  123,  124,  125,  126,  127,
        128,  129,  130,  131,  132,  133,  134,  135,  136,  138,  139,
        140,  143,  144,  145,  146,  147,  148,  149,  150,  151,  152,
        153,  155,  158,  160,  161,  162,  163,  164,  165,  166,  167,
        168,  169,  172,  173,  522,  527,  558,  560,  572,  586,  590,
        593,  597,  598,  599,  609,  619,  637,  638,  641,  650,  664,
        665,  681,  691,  702,  706,  713,  715,  722,  726,  749,  751,
        760,  764,  769,  785,  787,  788,  798,  801,  804,  806,  809,
        813,  818,  820,  823,  832,  847,  858,  859,  865,  878,  880,
        881,  882,  883,  899,  927,  928, 1009, 1018, 1022, 1036, 1052,
       1060, 1079, 1080, 1085, 1094, 1103, 1112, 1122, 1140, 1150, 1168,
       1174, 1231, 1232, 1233, 1234, 1235, 1238, 1239, 1240, 1241, 1245,
       1253, 1258, 1259, 1261, 1262, 1263, 1264, 1265, 1267, 1269, 1270,
       1271, 1272, 1274, 1275, 1278, 1279, 1280, 1281, 1283, 1284, 1285,
       1287, 1289, 1290, 1292, 1294, 1295, 1296, 1297, 1298, 1302, 1303,
       1306, 1307, 1308, 1314, 1315, 1328, 1329, 1332, 1336, 1337, 1339,
       1340, 1341, 1342, 1344, 1345, 1347, 1349, 1350, 1352, 1353, 1354,
       1356, 1359, 1363, 1364, 1365, 1366, 1367, 1368, 1371, 1373, 1374,
       1375, 1376, 1382, 1383, 1384, 1385, 1389, 1397, 1398, 1399, 1400,
       1405, 1406, 1411, 1413, 1418, 1419, 1422, 1425, 1428, 1429, 1430,
       1432, 1436, 1437, 1439, 1442, 1443, 1445, 1448, 1449, 1455, 1457,
       1461, 1463, 1464, 1466, 1467, 1468, 1473, 1474, 1475, 1476, 1486,
       1490, 1492, 1493, 1495, 1498, 1502, 1506, 1507, 1508, 1510, 1513,
       1516, 1517, 1518, 1520, 1522, 1524, 1526, 1527, 1528, 1529, 1530,
       1531, 1535, 1536, 1539, 1540, 1541, 1544, 1547, 1548, 1552, 1554,
       1559, 1560, 1561, 1563, 1566, 1568, 1572, 1580, 1581, 1584, 1590,
       1593, 1594, 1595, 1597, 1600, 1603, 1606, 1607, 1612, 1616, 1617,
       1622, 1626, 1627, 1628, 1629, 1637, 1641, 1648, 1649, 1650, 1651,
       1656, 1662, 1664, 1667, 1671, 1674, 1682, 1684, 1688, 1695, 1699,
       1701, 1705, 1712, 1721, 1729, 1734, 1740, 1743])

In [ ]:
#create a new folder with the disease_name_class writed
destination_path = f'/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/02_original_organized_by_disease_name/automatic/{disease_name_class}'
os.makedirs(destination_path, exist_ok=False)

In [ ]:
#copy all ids in the list to this destination path created
for i in range(len(list_files)):
  file_path = "/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/01_original/leaf/images/" + str(list_files[i]) + '.jpg'
  shutil.copy(file_path, destination_path)

#counting files to check how many images are copied

file_count = sum([len(files) for _, _, files in os.walk(destination_path)])

print(f"Number of files in {destination_path}: {file_count}")

Number of files in /content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/02_original_organized_by_disease_name/automatic/Rust: 349

#### phoma (This example was already runned, just check)

In [ ]:
df.query('phoma == 1 and miner == 0 and rust == 0 and cercospora == 0')

        id  predominant_stress  miner  rust  phoma  cercospora  severity
19      20                   3      0     0      1           0         2
231    232                   3      0     0      1           0         2
232    233                   3      0     0      1           0         1
233    234                   3      0     0      1           0         3
234    235                   3      0     0      1           0         2
...    ...                 ...    ...   ...    ...         ...       ...
1148  1149                   3      0     0      1           0         1
1178  1179                   3      0     0      1           0         1
1184  1185                   3      0     0      1           0         1
1194  1195                   3      0     0      1           0         2
1735  1736                   3      0     0      1           0         1

[342 rows x 7 columns]

In [ ]:
#write the name of the class in disease_name_class, this is the only thing that you need to change for each disease and run the rest of the code
disease_name_class = 'Phoma'
#here you write exaclty are in the csv 'miner', 'rust', 'phoma', 'cercospora', change for each disease, this code will select a list of ids by disease selected in this example is Miner
list_files = df.query('phoma == 1 and miner == 0 and rust == 0 and cercospora == 0')['id'].values

In [ ]:
list_files

array([  20,  232,  233,  234,  235,  236,  237,  238,  239,  240,  241,
        242,  243,  244,  245,  246,  247,  248,  249,  250,  251,  252,
        253,  254,  255,  256,  257,  258,  259,  260,  261,  262,  263,
        264,  265,  266,  267,  268,  269,  270,  271,  272,  273,  274,
        275,  276,  277,  278,  279,  280,  281,  282,  283,  284,  285,
        286,  287,  288,  289,  290,  291,  292,  293,  294,  295,  296,
        297,  298,  299,  300,  301,  302,  303,  304,  305,  306,  307,
        308,  309,  310,  311,  312,  313,  314,  315,  316,  317,  318,
        319,  320,  321,  322,  323,  324,  325,  326,  327,  328,  329,
        330,  331,  332,  333,  334,  335,  336,  337,  338,  339,  340,
        341,  342,  343,  344,  345,  346,  347,  348,  349,  350,  351,
        352,  353,  354,  355,  356,  357,  358,  359,  360,  361,  362,
        363,  364,  365,  366,  367,  368,  369,  370,  371,  372,  373,
        374,  375,  376,  377,  378,  379,  380,  381,  382,  383,  384,
        385,  386,  387,  388,  389,  390,  391,  392,  393,  394,  395,
        396,  397,  398,  399,  400,  401,  402,  403,  404,  405,  406,
        407,  408,  409,  410,  411,  412,  413,  414,  415,  416,  417,
        418,  419,  420,  421,  422,  423,  424,  425,  426,  427,  428,
        429,  430,  431,  432,  433,  434,  435,  436,  437,  438,  440,
        441,  442,  443,  444,  445,  448,  449,  450,  452,  453,  454,
        455,  456,  457,  458,  459,  460,  461,  462,  463,  464,  465,
        468,  469,  470,  471,  472,  473,  475,  476,  477,  478,  479,
        480,  481,  482,  483,  484,  485,  486,  487,  488,  489,  490,
        491,  492,  493,  495,  496,  497,  498,  499,  500,  501,  502,
        503,  505,  506,  507,  508,  509,  510,  511,  512,  513,  514,
        515,  516,  518,  519,  520,  521,  523,  524,  528,  529,  530,
        531,  532,  533,  534,  537,  538,  539,  540,  541,  542,  543,
        544,  545,  546,  547,  548,  549,  550,  551,  553,  554,  556,
        557,  559,  563,  564,  574,  591,  592,  595,  608,  610,  628,
        640,  645,  646,  647,  651,  654,  655,  657,  658,  661,  666,
        670,  673,  677,  683,  811,  996, 1148, 1149, 1179, 1185, 1195,
       1736])

In [ ]:
#create a new folder with the disease_name_class writed
destination_path = f'/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/02_original_organized_by_disease_name/automatic/{disease_name_class}'
os.makedirs(destination_path, exist_ok=False)

In [ ]:
#copy all ids in the list to this destination path created
for i in range(len(list_files)):
  file_path = "/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/01_original/leaf/images/" + str(list_files[i]) + '.jpg'
  shutil.copy(file_path, destination_path)

#counting files to check how many images are copied

file_count = sum([len(files) for _, _, files in os.walk(destination_path)])

print(f"Number of files in {destination_path}: {file_count}")

Number of files in /content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/02_original_organized_by_disease_name/automatic/Phoma: 342

#### cercospora (This example was already runned, just check)

In [ ]:
df.query('cercospora == 1 and miner == 0 and rust == 0 and phoma == 0')

        id  predominant_stress  miner  rust  phoma  cercospora  severity
61      62                   4      0     0      0           1         1
438    439                   4      0     0      0           1         1
465    466                   4      0     0      0           1         1
493    494                   4      0     0      0           1         1
516    517                   4      0     0      0           1         1
...    ...                 ...    ...   ...    ...         ...       ...
1717  1718                   4      0     0      0           1         1
1718  1719                   4      0     0      0           1         1
1724  1725                   4      0     0      0           1         1
1732  1733                   4      0     0      0           1         1
1745  1746                   4      0     0      0           1         1

[88 rows x 7 columns]

In [ ]:
#write the name of the class in disease_name_class, this is the only thing that you need to change for each disease and run the rest of the code
disease_name_class = 'Cercospora'
#here you write exaclty are in the csv 'miner', 'rust', 'phoma', 'cercospora', change for each disease, this code will select a list of ids by disease selected in this example is Miner
list_files = df.query('cercospora == 1 and miner == 0 and rust == 0 and phoma == 0')['id'].values

In [ ]:
list_files

array([  62,  439,  466,  494,  517,  525,  555,  566,  567,  569,  577,
        579,  611,  634,  653,  659,  668,  679,  692,  716,  742,  753,
        777,  829,  863,  889,  917,  918,  930, 1016, 1045, 1065, 1083,
       1090, 1091, 1101, 1175, 1200, 1202, 1205, 1215, 1220, 1221, 1249,
       1251, 1256, 1313, 1404, 1410, 1417, 1438, 1441, 1444, 1453, 1478,
       1485, 1496, 1501, 1549, 1550, 1553, 1573, 1576, 1577, 1582, 1591,
       1601, 1604, 1608, 1611, 1621, 1630, 1631, 1644, 1653, 1654, 1655,
       1673, 1675, 1677, 1700, 1706, 1708, 1718, 1719, 1725, 1733, 1746])

In [ ]:
#create a new folder with the disease_name_class writed
destination_path = f'/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/02_original_organized_by_disease_name/automatic/{disease_name_class}'
os.makedirs(destination_path, exist_ok=False)

In [ ]:
#copy all ids in the list to this destination path created
for i in range(len(list_files)):
  file_path = "/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/01_original/leaf/images/" + str(list_files[i]) + '.jpg'
  shutil.copy(file_path, destination_path)

#counting files to check how many images are copied

file_count = sum([len(files) for _, _, files in os.walk(destination_path)])

print(f"Number of files in {destination_path}: {file_count}")

Number of files in /content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Bracol/02_original_organized_by_disease_name/automatic/Cercospora: 88

# Roboflow

Choose a download code project to download

In [ ]:
!pip install roboflow

In [ ]:
from roboflow import Roboflow

In [ ]:
from roboflow import Roboflow
rf = Roboflow(api_key="your_api_key")
project = rf.workspace("sumatera-institute-of-technology").project("penyakit-daun-kopi")
dataset = project.version(5).download("coco")

loading Roboflow workspace...
loading Roboflow project...
Downloading Dataset Version Zip in Penyakit-Daun-Kopi-5 to coco: 100% [30456747 / 30456747] bytes

Extracting Dataset Version Zip to Penyakit-Daun-Kopi-5 in coco:: 100%|██████████| 508/508 [00:00<00:00, 1277.38it/s]

## Copy raw path dataset to our google drive

In [ ]:
#chose a name of path to copy your data in our drive
#dataset_name = 'Doencas_Computer_Vision_Project'
#dataset_name = '1000101010001010101010111_Computer_Vision_Project'
#dataset_name = 'Penyakit_Daun_Kopi_Computer_Vision_Project'
#dataset_name = 'Penyakit Daun NEW.v30-sehat-1000-bercak-1000-karat-1000.yolov8'
#dataset_name = 'cafe-detect.v11i.multiclass'
#dataset_name = 'Penyakit Daun NEW.v30-sehat-1000-bercak-1000-karat-1000.yolov8'
dataset_name = 'your_dataset_name_downloaded'

In [ ]:
#you need to add a shortcut to your drive for SaoPauloChatper...
#source_path = '/content/Doencas-1'
#source_path = '/content/1000101010001010101010111-3'
#source_path = '/content/Penyakit-Daun-Kopi-5'
#source_path = '/content/Penyakit-Daun-NEW-30'
#source_path = '/content/cafe-detect-16'
source_path = '/content/your_dataset_name_downloaded'

#chose a name of path to copy your data
destination_path = f'/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/{dataset_name}/01_original'

In [ ]:
shutil.copytree(source_path, destination_path)

'/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/Penyakit Daun NEW.v30-sehat-1000-bercak-1000-karat-1000.yolov8/01_original'

In [ ]:
#counting files to check, the process can be slow

file_count = sum([len(files) for _, _, files in os.walk(destination_path)])

print(f"Number of files in {destination_path}: {file_count}")

Number of files in /content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/Penyakit Daun NEW.v30-sehat-1000-bercak-1000-karat-1000.yolov8/01_original: 3005

## Organize files by the disease since we receive all labels in the same path

In [ ]:
# Identify all paths available
paths = ['valid', 'train', 'test']

In [ ]:
#put the name of dataset downloadede by API
#dataset_name_downloaded = 'Doencas-1'
#dataset_name_downloaded = '1000101010001010101010111-3'
#dataset_name_downloaded = 'Penyakit_Daun_Kopi_Computer_Vision_Project'
#dataset_name_downloaded = 'Penyakit-Daun-NEW-30'
#dataset_name_downloaded = 'cafe-detect-16'
dataset_name_downloaded = 'your_dataset_name_downloaded'

In [ ]:
rows = []
# Iterate through each path
for path in paths:
    json_file = f'/content/{dataset_name_downloaded}/{path}/_annotations.coco.json'  # Update this with the correct path to your JSON file

    # Read the JSON file
    with open(json_file, 'r') as file:
        data = json.load(file)

    for i in range(len(data['images'])):
        image_id = data['images'][i]['id']
        category_id = data['annotations'][i]['category_id']
        file_name = data['images'][i]['file_name']
        height = data['images'][i]['height']
        width = data['images'][i]['width']

        rows.append([image_id, category_id, path, file_name, height, width])

# Create a DataFrame
df = pd.DataFrame(rows, columns=['id', 'category_id', 'path', 'file_name', 'height', 'width'])

In [ ]:
df_category = pd.DataFrame(data['categories'])

In [ ]:
df_category

   id                            name                   supercategory
0   0  Penyakit-Daun-Tanaman-Kopi-New                            none
1   1                     Daun Bercak  Penyakit-Daun-Tanaman-Kopi-New
2   2                      Daun Karat  Penyakit-Daun-Tanaman-Kopi-New
3   3                      Daun Sehat  Penyakit-Daun-Tanaman-Kopi-New

In [ ]:
df_merged = pd.merge(df,df_category, left_on='category_id', right_on='id', how='left')

In [ ]:
df_merged

,id_x,category_id,path,file_name,height,width,id_y,name,supercategory
0,0,3,valid,IMG_20230320_113019-432x768_jpg.rf.6003a9f75d8...,640,640,3,Daun Sehat,Penyakit-Daun-Tanaman-Kopi-New
1,1,2,valid,IMG20230520112034-576x768_jpg.rf.600e913029f65...,640,640,2,Daun Karat,Penyakit-Daun-Tanaman-Kopi-New
2,2,2,valid,IMG20230520105034-432x768_jpg.rf.603d0baaaf5fb...,640,640,2,Daun Karat,Penyakit-Daun-Tanaman-Kopi-New
3,3,1,valid,IMG_20221126_121259-576x768_jpg.rf.60459f85bc3...,640,640,1,Daun Bercak,Penyakit-Daun-Tanaman-Kopi-New
4,4,3,valid,IMG_20230320_111458-432x768_jpg.rf.6071f818309...,640,640,3,Daun Sehat,Penyakit-Daun-Tanaman-Kopi-New
...,...,...,...,...,...,...,...,...,...
2995,296,3,test,IMG_20230320_115755-432x768_jpg.rf.f97d72f465d...,640,640,3,Daun Sehat,Penyakit-Daun-Tanaman-Kopi-New
2996,297,3,test,IMG_20221126_114543-434x768_jpg.rf.f1c08d8ccd0...,640,640,3,Daun Sehat,Penyakit-Daun-Tanaman-Kopi-New
2997,298,2,test,IMG20230520105245-576x768_jpg.rf.ffcd61aee35d1...,640,640,2,Daun Karat,Penyakit-Daun-Tanaman-Kopi-New
2998,299,1,test,bercak-295-1022x768_jpg.rf.ffe5a234fd96bbc3a39...,640,640,1,Daun Bercak,Penyakit-Daun-Tanaman-Kopi-New
2999,300,2,test,IMG20230520105513-576x768_jpg.rf.fb428df3321b3...,640,640,2,Daun Karat,Penyakit-Daun-Tanaman-Kopi-New

In [ ]:
df_merged['entire_path'] = dataset_name_downloaded + '/'  + df_merged['path'] + '/' + df_merged['file_name']

In [ ]:
df_merged

,id_x,category_id,path,file_name,height,width,id_y,name,supercategory,entire_path
0,0,3,valid,IMG_20230320_113019-432x768_jpg.rf.6003a9f75d8...,640,640,3,Daun Sehat,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/valid/IMG_20230320_113019...
1,1,2,valid,IMG20230520112034-576x768_jpg.rf.600e913029f65...,640,640,2,Daun Karat,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/valid/IMG20230520112034-5...
2,2,2,valid,IMG20230520105034-432x768_jpg.rf.603d0baaaf5fb...,640,640,2,Daun Karat,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/valid/IMG20230520105034-4...
3,3,1,valid,IMG_20221126_121259-576x768_jpg.rf.60459f85bc3...,640,640,1,Daun Bercak,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/valid/IMG_20221126_121259...
4,4,3,valid,IMG_20230320_111458-432x768_jpg.rf.6071f818309...,640,640,3,Daun Sehat,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/valid/IMG_20230320_111458...
...,...,...,...,...,...,...,...,...,...,...
2995,296,3,test,IMG_20230320_115755-432x768_jpg.rf.f97d72f465d...,640,640,3,Daun Sehat,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/test/IMG_20230320_115755-...
2996,297,3,test,IMG_20221126_114543-434x768_jpg.rf.f1c08d8ccd0...,640,640,3,Daun Sehat,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/test/IMG_20221126_114543-...
2997,298,2,test,IMG20230520105245-576x768_jpg.rf.ffcd61aee35d1...,640,640,2,Daun Karat,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/test/IMG20230520105245-57...
2998,299,1,test,bercak-295-1022x768_jpg.rf.ffe5a234fd96bbc3a39...,640,640,1,Daun Bercak,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/test/bercak-295-1022x768_...
2999,300,2,test,IMG20230520105513-576x768_jpg.rf.fb428df3321b3...,640,640,2,Daun Karat,Penyakit-Daun-Tanaman-Kopi-New,Penyakit-Daun-NEW-30/test/IMG20230520105513-57...

In [ ]:
df_merged['name'].unique()

array(['Daun Sehat', 'Daun Karat', 'Daun Bercak'], dtype=object)

### In this block, you need to iterate by all classes your dataset has and change the name of disiease_raw_name and the disease_name_class you are adopting. Remember to try to keep the similar names that are already used in the other datasets (rust, Miner, Phoma, Cescospora ... )

In [ ]:
#disiease_raw_name = 'Daun Sehat'
#disease_name_class = 'Healthy'

#disiease_raw_name = 'Daun Karat'
#disease_name_class = 'Rust'

disiease_raw_name = 'Daun Bercak'
disease_name_class = 'Cescospora'

#disiease_raw_name = 'rust'
#disease_name_class = 'Rust'


#disiease_raw_name = 'ferrugemrotation'
#disease_name_class = 'Rust'

#disiease_raw_name = 'phomarotation'
#disease_name_class = 'Phoma'

#disiease_raw_name = 'bicho_mineirorotation'
#disease_name_class = 'Miner'

#disiease_raw_name = 'Ferrugem'
#disease_name_class = 'Rust'

#disiease_raw_name = 'Cercospora'
#disease_name_class = 'Cescospora'

In [ ]:
#need to set manually
list_files = df_merged.loc[df_merged['name'] == disiease_raw_name]['entire_path']

In [ ]:
list_files

3       Penyakit-Daun-NEW-30/valid/IMG_20221126_121259...
5       Penyakit-Daun-NEW-30/valid/IMG_20221126_122036...
14      Penyakit-Daun-NEW-30/valid/IMG_20221126_120244...
16      Penyakit-Daun-NEW-30/valid/IMG_2305-576x768_JP...
18      Penyakit-Daun-NEW-30/valid/IMG_20221126_115533...
                              ...
2989    Penyakit-Daun-NEW-30/test/IMG20221126121637-57...
2992    Penyakit-Daun-NEW-30/test/IMG_2288-1024x768_JP...
2993    Penyakit-Daun-NEW-30/test/bercak-304-1022x768_...
2994    Penyakit-Daun-NEW-30/test/IMG_20221126_112125-...
2998    Penyakit-Daun-NEW-30/test/bercak-295-1022x768_...
Name: entire_path, Length: 998, dtype: object

In [ ]:
list_files.iloc[0]

'Penyakit-Daun-NEW-30/valid/IMG_20221126_121259-576x768_jpg.rf.60459f85bc3772c1ee94f28e867a427c.jpg'

In [ ]:
destination_path = f'/content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/{dataset_name}/02_original_organized_by_disease/{disease_name_class}'
os.makedirs(destination_path, exist_ok=False)

In [ ]:
for i in range(len(list_files)):
  file_path = "/content/" + list_files.iloc[i]
  shutil.copy(file_path, destination_path)

In [ ]:
#counting files to check, the process can be slow

file_count = sum([len(files) for _, _, files in os.walk(destination_path)])

print(f"Number of files in {destination_path}: {file_count}")

Number of files in /content/drive/MyDrive/SaoPauloChapter_Plants-Disease_2023-Aug-02/Task-2-Data Collection & Preprocessing/data/approach_1/01_original_datasets/Penyakit Daun NEW.v30-sehat-1000-bercak-1000-karat-1000.yolov8/02_original_organized_by_disease/Cescospora: 998